[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'vim-fugitive'
hook_add = 'call coil398#init#lightline#hook_add()'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = 'call coil398#init#gtags#hook_add()'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
    let g:gen_tags#ctags_auto_gen = 1
    let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'call coil398#init#vim_quickrun#hook_add()'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
depends = 'vim-quickrun'

[[plugins]]
repo = 'skywind3000/asyncrun.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = 'call coil398#init#vim_quickhl#hook_add()'
