[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = ['c', 'cpp']

# [[plugins]]
# repo = 'hdima/python-syntax'
# on_ft = 'python'

# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# on_ft = 'python'
# hook_source = 'call coil398#init#jedi_vim#hook_source()'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'
