[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
on_cmd = ['Denite']
hook_add = 'call coil398#init#denite#hook_add()'
hook_post_source = 'call coil398#init#denite#hook_post_source()'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path='.*'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_source = ['denite.nvim']

[[plugins]]
repo = 'ozelentok/denite-gtags'
on_path = '.*'
on_source = ['denite.nvim']
hook_add = 'call coil398#init#denitegtags#hook_add()'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'call coil398#init#neosnippet#hook_source()'


[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = {n = '<Plug>'}
depends = 'unite.vim'
hook_add = 'call coil398#init#vimshell#hook_add()'
