[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = 'call coil398#init#deoplete#hook_source()'

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
on_ft = ['c', 'cpp']
depends = 'deoplete.nvim'
hook_source = '''
    autocmd FileType c,cpp let b:clang2_orig_maps = {}
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = 'deoplete.nvim'
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
depends = 'deoplete.nvim'
on_i = 1
on_ft = 'go'
build = 'make'
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
depends = 'deoplete.nvim'
on_i = 1
on_ft = 'javascript'

[[plugins]]
repo = 'mhartington/nvim-typescript'
depends = ['deoplete.nvim']
on_i = 1
on_ft = 'typescript'
hook_add = '''
    let g:nvim_typescript#vue_support = 1
'''

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = 'typescript'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-zsh'
depends = 'deoplete.nvim'
on_ft = 'sh'
on_i = 1
